apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: ingress-haproxy
spec:
  ports:
  - name: port-1
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 443
  - name: port-3
    nodePort: 31936
    port: 1936
    protocol: TCP
    targetPort: 1936
  selector:
    run: haproxy-ingress
  sessionAffinity: None
  type: NodePort

