apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    policies.kyverno.io/patches: |
      podControllerAnnotation.disallow-host-network-port.kyverno.io: added /spec/template/metadata/annotations
  generation: 32
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: ingress-haproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: haproxy-ingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pod-policies.kyverno.io/autogen-applied: "true"
      labels:
        run: haproxy-ingress
      namespace: ingress-haproxy
    spec:
      serviceAccountName: haproxy-ingress-serviceaccount
      containers:
      - args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --default-ssl-certificate=$(POD_NAMESPACE)/kube-all-inusca-svc.dev.nibr.novartis.net
        - --configmap=$(POD_NAMESPACE)/haproxy-configmap
        - --reload-strategy=native
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ghcr.io/nirmata/haproxy-ingress:v0.9-beta.3
        imagePullPolicy: IfNotPresent
        name: haproxy-ingress
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 1936
          name: stat
          protocol: TCP



